### ISSUE TITLE
Is this necessary with the app ups power monitor for mac?

### ISSUE THREAD

**Issue by ExtremeNoob** [dniklewicz/UPSPowerHelper#2]
Hi!  The website linked on the app page does not work neither does www.vallios.com so I'm trying here.  I just installed a NUT server on a pi4 and installed ups power monitor.  The app sees the ups but when I try to add the imac to the power guard list, I get : Client unreachable.  Please check if the Power Server is running on this device.
What cab I do to check this?
Cheers!
<img width="420" alt="Screen Shot 2023-08-09 at 5 58 20 AM" src="https://github.com/dniklewicz/UPSPowerHelper/assets/81020773/fdcb9eeb-9a62-4114-a626-96c73673c0a1">

**Comment by dniklewicz** [comment]
Hey @ExtremeNoob! Our support page was down but it should work now.
In order to configure `Power Guard`, you need to install additional tool called `Power Server` on the machine you want to shut down on low battery event. 
Please find the instructions here: https://apps.dniklewicz.com/ups-mac/powerguard.html

**Comment by ExtremeNoob** [comment]
Hi!  Thanks for the prompt response.  I followed the instructions and everything works fine now :)  I had initially trouble because I am using a vpn and your site didn't like that...
Cheers!

**Comment by dniklewicz** [comment]
That's true, there are geographical restrictions for few countries so VPNs can be affected as well.
I'm glad everything works now :)
